// NOTE THIS IS NOT OREZ NODE THIS IS NOT A GOOD REFERENCE BECAUSE ITS OUR EARLY GUESS AT WHAT COULD WORK
// DO NOT STUDY THIS, THE OTHER STUFF IN SRC IS WHERE YOU EANT TO LOOK

/**
 * zero-cache embedded runner for browser Web Workers.
 *
 * same pattern as the CF embed but for browser environments:
 *
 *   postgres           → orez/worker/shims/postgres  (PGlite-backed)
 *   @rocicorp/zero-sqlite3 → orez/worker/shims/sqlite (sql.js or in-memory)
 *   fastify            → orez/worker/shims/fastify   (route capture)
 *   ws                 → orez/worker/shims/ws        (MessagePort/WebSocket)
 *
 * the consumer's bundler (esbuild/vite) must configure these aliases
 * plus Node.js polyfills. use getBrowserBuildConfig() for the alias map.
 *
 * usage:
 *
 *   import { startZeroCacheEmbedBrowser } from 'orez/worker/browser-embed'
 *
 *   const zc = await startZeroCacheEmbedBrowser({
 *     pglite: pg,
 *     sqlite: sqlJsDb, // optional — sql.js Database instance
 *   })
 *
 *   // connect a Zero client via WebSocket-like object
 *   zc.handleWebSocket(wsOrPort)
 *
 *   // or handle HTTP requests (push/pull)
 *   const result = await zc.handleHttp({ method: 'GET', url: '/' })
 */

import { EventEmitter } from 'node:events'

import { createBrowserProxy, type BrowserProxy } from '../pg-proxy-browser.js'
import { deleteReplicationState, resetReplicationState } from '../replication/handler.js'
import { handleDisabledBrowserAdminRequest } from './browser-admin.js'
import {
  dispatcherFastifyForCFInstance,
  postgresURLForCFInstance,
  registerCFInstanceRuntime,
  releaseCFInstanceRuntime,
  setCFInstanceEnv,
  setCFInstanceProxy,
  sqliteDirectoryForCFInstance,
  sqlitePathForCFInstance,
  type CFInstanceRuntime,
} from './cf-instance-runtime.js'
import { sweepCFInstanceSqliteHandles } from './embed-generation.js'
import { acquireZeroProcessEnv } from './shims/zero-process-env.js'
// static import so the bundler can follow the dependency tree.
import { runWorker as _runWorker } from './zero-cache-run-worker.js'

import type { HttpRequest, HttpResponse } from './browser-admin.js'
import type { PGlite } from '@electric-sql/pglite'

export type { HttpRequest, HttpResponse } from './browser-admin.js'

const runWorkerFn = _runWorker as (
  parent: unknown,
  env: Record<string, string>
) => Promise<void>

export interface ZeroCacheEmbedBrowserOptions {
  /** PGlite instance */
  pglite: PGlite

  /** optional logical identity; a unique browser identity is generated by default. */
  instanceId?: string

  /**
   * sql.js Database instance for SQLite replica storage.
   * if not provided, uses an in-memory stub (limited functionality).
   */
  sqlite?: unknown

  /** zero app ID (default: 'zero') */
  appId?: string

  /** publication names */
  publications?: string[]

  /** additional env vars passed to zero-cache */
  env?: Record<string, string>

  /** timeout in ms waiting for zero-cache ready (default: 30000) */
  readyTimeout?: number

  /**
   * intercept browser-mode orez admin routes before they reach zero-cache.
   *
   * browser embeds do not run the node admin dashboard or log store. leaving
   * `/__orez/*` to fall through to zero-cache makes disabled admin look like
   * an app/zero route miss. keep the contract explicit by returning empty
   * admin responses for the small read-only surface and 404 for the rest.
   * default: true.
   */
  disableAdminApi?: boolean
}

/** WebSocket-like object — matches CF WebSocket, browser WebSocket, or MessagePort adapter */
interface WsLike {
  readyState: number
  send(data: string | ArrayBuffer | ArrayBufferView): void
  close(code?: number, reason?: string): void
  addEventListener(type: string, handler: (event: any) => void): void
  removeEventListener(type: string, handler: (event: any) => void): void
}

export interface ZeroCacheEmbedBrowser {
  /** whether zero-cache is ready */
  readonly ready: boolean

  /**
   * handle a WebSocket connection from a Zero client.
   * accepts any WebSocket-like object (browser WebSocket, MessagePort adapter, etc.)
   * feeds it into zero-cache's handoff mechanism.
   */
  handleWebSocket(ws: WsLike, url?: string): void

  /**
   * handle an HTTP request (push/pull/health).
   * for environments without the Fetch API Request/Response.
   */
  handleHttp(request: HttpRequest): Promise<HttpResponse>

  /** stop zero-cache */
  stop(): Promise<void>
}

export async function startZeroCacheEmbedBrowser(
  opts: ZeroCacheEmbedBrowserOptions
): Promise<ZeroCacheEmbedBrowser> {
  const appId = opts.appId || 'zero'
  const publications = opts.publications?.join(',') || `orez_${appId}_public`
  const readyTimeout = opts.readyTimeout ?? 30000
  const disableAdminApi = opts.disableAdminApi ?? true
  const requestedInstanceId = opts.instanceId?.trim()
  const instanceId = requestedInstanceId || `browser-${crypto.randomUUID()}`
  const { createInMemoryStorage, createSqlJsStorage } =
    await import('./shims/sqlite-browser.js')
  const doSqlite = opts.sqlite
    ? createSqlJsStorage(opts.sqlite as any)
    : createInMemoryStorage()
  const runtime = registerCFInstanceRuntime({
    doSqlite,
    env: opts.env ?? {},
    instanceId,
    pgPassword: '',
    pgUser: 'user',
  })
  const releaseProcessEnv = acquireZeroProcessEnv()
  let processEnvReleased = false
  let proxy: BrowserProxy | null = null
  let isReady = false
  let workerDone = true
  let runWorkerPromise: Promise<void> | null = null
  let fastifyInstance: any = null
  let stopping = false
  let cleanupPromise: Promise<void> | null = null

  const parent = new EventEmitter() as EventEmitter & {
    send: (msg: unknown) => boolean
    kill: (signal?: string) => void
    pid: number
  }

  const parentEmitter = new EventEmitter()

  parent.send = (message: unknown) => {
    parentEmitter.emit('message', message)
    return true
  }
  parent.kill = (signal = 'SIGTERM') => {
    parent.emit(signal, signal)
  }
  parent.pid = 1
  const wrappedParent = new Proxy(parent, {
    get(target, prop, receiver) {
      if (prop === 'onMessageType') {
        return (type: string, handler: (msg: unknown) => void) => {
          target.on('message', (data: unknown) => {
            if (Array.isArray(data) && data.length === 2 && data[0] === type) {
              handler(data[1])
            }
          })
          return receiver
        }
      }
      if (prop === 'onceMessageType') {
        return (type: string, handler: (msg: unknown) => void) => {
          const listener = (data: unknown) => {
            if (Array.isArray(data) && data.length === 2 && data[0] === type) {
              target.off('message', listener)
              handler(data[1])
            }
          }
          target.on('message', listener)
          return receiver
        }
      }
      const value = Reflect.get(target, prop, target)
      if (typeof value !== 'function') return value
      return (...args: unknown[]) => {
        const result = value.apply(target, args)
        return result === target ? receiver : result
      }
    },
  })

  const cleanup = () => {
    if (cleanupPromise) return cleanupPromise
    stopping = true
    isReady = false
    cleanupPromise = (async () => {
      const errors: unknown[] = []
      let resourceCleanupFailed = false
      if (!workerDone) wrappedParent.kill('SIGTERM')
      if (runWorkerPromise && !workerDone) {
        const stopped = await Promise.race([
          runWorkerPromise.then(
            () => true,
            () => true
          ),
          new Promise<false>((resolve) => setTimeout(() => resolve(false), 5_000)),
        ])
        if (!stopped) {
          resourceCleanupFailed = true
          errors.push(new Error('zero-cache browser embed: worker did not terminate'))
        }
      }

      try {
        await proxy?.close()
      } catch (error) {
        resourceCleanupFailed = true
        errors.push(error)
      }
      try {
        sweepCFInstanceSqliteHandles(runtime)
      } catch (error) {
        resourceCleanupFailed = true
        errors.push(error)
      }

      if (workerDone && !resourceCleanupFailed) {
        deleteReplicationState(runtime.instanceId)
        releaseCFInstanceRuntime(runtime)
      }
      parentEmitter.removeAllListeners()
      if (workerDone) parent.removeAllListeners()
      if (workerDone && !processEnvReleased) {
        processEnvReleased = true
        releaseProcessEnv()
      }
      if (errors.length > 0) {
        throw new AggregateError(errors, 'zero-cache browser embed: teardown failed')
      }
    })()
    return cleanupPromise
  }

  try {
    proxy = await createBrowserProxy(opts.pglite, {
      debugWire: opts.env?.OREZ_DEBUG_WIRE === '1',
      instanceId: runtime.instanceId,
      pgPassword: '',
      pgUser: 'user',
      singleDb: true,
    })
    setCFInstanceProxy(runtime, (port) => proxy?.handleConnection(port))

    const env: Record<string, string> = {
      SINGLE_PROCESS: '1',
      NODE_ENV: 'development',
      ZERO_APP_ID: appId,
      ZERO_APP_PUBLICATIONS: publications,
      ZERO_LOG_LEVEL: opts.env?.ZERO_LOG_LEVEL || 'info',
      ZERO_NUM_SYNC_WORKERS: opts.env?.ZERO_NUM_SYNC_WORKERS || '1',
      ZERO_ENABLE_QUERY_PLANNER: 'false',
      ...opts.env,
      ZERO_UPSTREAM_DB: postgresURLForCFInstance(runtime.instanceId, 'postgres', 'user'),
      ZERO_CVR_DB: postgresURLForCFInstance(runtime.instanceId, 'zero_cvr', 'user'),
      ZERO_CHANGE_DB: postgresURLForCFInstance(runtime.instanceId, 'zero_cdb', 'user'),
      ZERO_REPLICA_FILE: sqlitePathForCFInstance(runtime.instanceId),
      ZERO_STORAGE_DB_TMP_DIR: sqliteDirectoryForCFInstance(runtime.instanceId),
      ZERO_PORT: String(runtime.basePort),
      ZERO_TASK_ID: `orez-browser-${runtime.encodedId}`,
    }
    setCFInstanceEnv(runtime, env)
    resetReplicationState(runtime.instanceId, env)

    const readyPromise = new Promise<void>((resolve, reject) => {
      const timeout = setTimeout(() => {
        reject(
          new Error(
            `zero-cache browser embed: timed out waiting for ready after ${readyTimeout}ms`
          )
        )
      }, readyTimeout)
      parentEmitter.on('message', (msg: unknown) => {
        if (Array.isArray(msg) && msg[0] === 'ready') {
          clearTimeout(timeout)
          isReady = true
          resolve()
        }
      })
    })

    workerDone = false
    runWorkerPromise = Promise.resolve().then(() => runWorkerFn(wrappedParent, env))
    const workerStartup = runWorkerPromise.then(
      () => {
        workerDone = true
        if (!isReady)
          throw new Error('zero-cache browser embed: worker exited before ready')
      },
      (error) => {
        workerDone = true
        throw error
      }
    )
    await Promise.race([readyPromise, workerStartup])
    void workerStartup.catch(() => {
      if (!stopping) isReady = false
    })

    const dispatcherDeadline = Date.now() + 5_000
    while (!fastifyInstance && Date.now() < dispatcherDeadline) {
      fastifyInstance = dispatcherFastifyForCFInstance(runtime.instanceId)
      if (!fastifyInstance) await new Promise((resolve) => setTimeout(resolve, 50))
    }
    if (!fastifyInstance) {
      throw new Error('zero-cache browser embed: dispatcher did not register')
    }

    return {
      get ready() {
        return isReady
      },

      async handleWebSocket(ws: WsLike, url = '/', headers?: Record<string, string>) {
        if (!isReady) return
        const handoffMsg = {
          message: { url, headers: headers || {}, method: 'GET' },
          head: new Uint8Array(0),
        }
        for (const instance of runtime.fastifyInstances) {
          if ((instance as any)?.tryHandoff?.(handoffMsg, ws)) return
        }
        fastifyInstance?.server?.emit('message', ['handoff', handoffMsg], ws)
      },

      async handleHttp(request: HttpRequest): Promise<HttpResponse> {
        if (disableAdminApi) {
          const adminResponse = handleDisabledBrowserAdminRequest(request)
          if (adminResponse) return adminResponse
        }
        if (!isReady || !fastifyInstance?.inject) {
          return { status: 503, headers: {}, body: 'not ready' }
        }
        const result = await fastifyInstance.inject({
          method: request.method,
          url: request.url,
          headers: request.headers || {},
          payload: request.body,
        })
        return {
          status: result.statusCode,
          headers: result.headers,
          body: result.body,
        }
      },

      stop: cleanup,
    }
  } catch (error) {
    await cleanup().catch(() => {})
    throw error
  }
}
