name = "orez-rust-sync"
main = "src/harness-worker.ts"
compatibility_date = "2026-06-01"
account_id = "6afff1f79e2fd12f1cfd1bfe1dfd08d1"
workers_dev = true

[[durable_objects.bindings]]
name = "SYNC_DO"
class_name = "SyncDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncDurableObject"]

[observability]
enabled = true
