// soot-native: Soot's sync host binary for local development.
//
// reads a JSON config (generated by scripts/lib/sync-native-config.ts),
// builds a SyncNativeHost, and starts serving on the given port.
//
// the app worker routes SQLite reads and writes through this host's admin SQL
// endpoint. each namespace file is the project's only authoritative database,
// so it must never be treated as an evictable replica cache. for push, the
// MutateFn is a no-op because application mutations go through the TypeScript
// API and then return here through admin SQL.

use std::fs;
use std::path::PathBuf;
use std::sync::Arc;

use axum::http::HeaderMap;
use serde::Deserialize;
use serde_json::Value;
use sync_core::SyncDb;
use sync_core::schema::{TableSpec, Tables};
use sync_core::value::ZeroColumnType;
use sync_native::engine::{InitFn, MutateFn};
use sync_native::retain::RetentionPolicy;
use sync_native::{AuthFn, SyncNativeConfig, SyncNativeHost, SyncNativeSecurity};

// ---- config file shapes ---------------------------------------------------

#[derive(Deserialize)]
struct ConfigFile {
    #[serde(default)]
    tables: Vec<TableDef>,
    #[serde(default)]
    ddl: Vec<String>,
    #[serde(default = "default_retain")]
    retain_changes: i64,
    #[serde(default)]
    query_aware: bool,
    #[serde(default)]
    visibility_enabled: bool,
}

#[derive(Deserialize)]
struct TableDef {
    name: String,
    columns: Vec<ColumnDef>,
    #[serde(default)]
    primary_key: Vec<String>,
}

#[derive(Deserialize)]
struct ColumnDef {
    name: String,
    #[serde(rename = "type")]
    col_type: String,
}

fn default_retain() -> i64 {
    4096
}

// ---- helpers ---------------------------------------------------------------

fn parse_column_type(s: &str) -> ZeroColumnType {
    match s {
        "string" => ZeroColumnType::String,
        "number" => ZeroColumnType::Number,
        "boolean" => ZeroColumnType::Boolean,
        "json" => ZeroColumnType::Json,
        "null" => ZeroColumnType::Null,
        _ => ZeroColumnType::String,
    }
}

fn build_tables(defs: &[TableDef]) -> Tables {
    let mut tables = Tables::new();
    for t in defs {
        let columns: Vec<(String, ZeroColumnType)> = t
            .columns
            .iter()
            .map(|c| (c.name.clone(), parse_column_type(&c.col_type)))
            .collect();
        tables.push(
            t.name.clone(),
            TableSpec {
                columns,
                primary_key: t.primary_key.clone(),
            },
        );
    }
    tables
}

// ---- callbacks -------------------------------------------------------------

fn make_init(ddl: Vec<String>) -> InitFn {
    Arc::new(move |db: &mut dyn SyncDb| {
        for stmt in &ddl {
            db.exec(stmt, &[]).map_err(|e| format!("ddl error: {e}"))?;
        }
        Ok(())
    })
}

fn make_mutate() -> MutateFn {
    // in local dev, the app worker owns the API and sends its drizzle SQL back
    // through this host's admin endpoint. push mutations from zero clients are
    // accepted (LMID advances) but not applied; application writes use that API.
    Arc::new(|_db: &mut dyn SyncDb, _name: &str, _args: &Value, _user_id: &str| Ok(()))
}

fn make_auth() -> AuthFn {
    Arc::new(|headers: &HeaderMap| {
        let value = headers.get("authorization")?.to_str().ok()?;
        let token = value.strip_prefix("Bearer ")?;
        // the app worker mints tokens of the form "token-<userId>"
        token
            .strip_prefix("token-")
            .filter(|user_id| !user_id.is_empty())
            .map(str::to_string)
    })
}

// ---- cli -------------------------------------------------------------------

#[derive(Default)]
struct Args {
    config: Option<String>,
    data_dir: Option<String>,
    port: Option<u16>,
    admin_token: Option<String>,
    allowed_origins: Vec<String>,
}

fn parse_args() -> Args {
    let mut args = Args::default();
    let mut i = 1;
    let argv: Vec<String> = std::env::args().collect();
    while i < argv.len() {
        match argv[i].as_str() {
            "--config" => {
                i += 1;
                if i < argv.len() {
                    args.config = Some(argv[i].clone());
                }
            }
            "--data-dir" => {
                i += 1;
                if i < argv.len() {
                    args.data_dir = Some(argv[i].clone());
                }
            }
            "--port" => {
                i += 1;
                if i < argv.len() {
                    args.port = argv[i].parse().ok();
                }
            }
            "--admin-token" => {
                i += 1;
                if i < argv.len() {
                    args.admin_token = Some(argv[i].clone());
                }
            }
            "--allow-origin" => {
                i += 1;
                if i < argv.len() {
                    args.allowed_origins.push(argv[i].clone());
                }
            }
            _ => {}
        }
        i += 1;
    }
    args
}

// ---- main ------------------------------------------------------------------

#[tokio::main]
async fn main() {
    let args = parse_args();

    let config_path = args.config.unwrap_or_else(|| {
        // default relative to soot root: .orez/data/soot-sync-config.json
        let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
        cwd.join(".orez/data/soot-sync-config.json")
            .to_string_lossy()
            .to_string()
    });

    let data_dir = args.data_dir.unwrap_or_else(|| {
        let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
        cwd.join(".orez/sync-native").to_string_lossy().to_string()
    });

    let port = args
        .port
        .or_else(|| std::env::var("PORT_ZERO").ok().and_then(|s| s.parse().ok()))
        .unwrap_or(7849);

    let raw = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("failed to read config at {config_path}: {e}"));

    let cfg: ConfigFile =
        serde_json::from_str(&raw).unwrap_or_else(|e| panic!("invalid config: {e}"));

    let tables = build_tables(&cfg.tables);
    let initialize = make_init(cfg.ddl);
    let mutate = make_mutate();
    let authenticate = make_auth();

    let config = SyncNativeConfig {
        tables,
        initialize,
        mutate,
        visible: None,
        authenticate,
        retain_changes: cfg.retain_changes,
        max_change_rows: sync_core::pull::Caps::default().max_change_rows,
        visibility_enabled: cfg.visibility_enabled,
        query_aware: cfg.query_aware,
        query_resolution: None,
        admin_tx_lease: sync_native::DEFAULT_ADMIN_TX_LEASE,
        // these files are authoritative project databases, not derived caches.
        retention: RetentionPolicy::disabled(),
    };

    let mut security = args
        .admin_token
        .or_else(|| std::env::var("SYNC_NATIVE_ADMIN_TOKEN").ok())
        .map(SyncNativeSecurity::with_admin_token)
        .unwrap_or_else(SyncNativeSecurity::process_random);
    for origin in args.allowed_origins {
        security = security.allow_origin(origin);
    }
    let host = SyncNativeHost::new_with_security(config, PathBuf::from(&data_dir), security);
    host.run(port).await;
}
