export type SyncNativeLibc = 'glibc' | 'musl'

export interface SyncNativePlatform {
  id: string
  target: string
  runner: string
  npmPackage: string
  packageDir: string
  os: NodeJS.Platform
  cpu: NodeJS.Architecture
  libc?: SyncNativeLibc
  executable: 'sync-native' | 'sync-native.exe'
}

const platform = (
  id: string,
  target: string,
  runner: string,
  os: NodeJS.Platform,
  cpu: NodeJS.Architecture,
  libc?: SyncNativeLibc
): SyncNativePlatform => ({
  id,
  target,
  runner,
  npmPackage: `orez-sync-native-${id}`,
  packageDir: `packages/sync-native-${id}`,
  os,
  cpu,
  libc,
  executable: os === 'win32' ? 'sync-native.exe' : 'sync-native',
})

export const SYNC_NATIVE_PLATFORMS: readonly SyncNativePlatform[] = [
  platform('darwin-arm64', 'aarch64-apple-darwin', 'macos-15', 'darwin', 'arm64'),
  platform('darwin-x64', 'x86_64-apple-darwin', 'macos-15-intel', 'darwin', 'x64'),
  platform(
    'linux-arm64-gnu',
    'aarch64-unknown-linux-gnu',
    'ubuntu-22.04-arm',
    'linux',
    'arm64',
    'glibc'
  ),
  platform(
    'linux-arm64-musl',
    'aarch64-unknown-linux-musl',
    'ubuntu-22.04-arm',
    'linux',
    'arm64',
    'musl'
  ),
  platform(
    'linux-x64-gnu',
    'x86_64-unknown-linux-gnu',
    'ubuntu-22.04',
    'linux',
    'x64',
    'glibc'
  ),
  platform(
    'linux-x64-musl',
    'x86_64-unknown-linux-musl',
    'ubuntu-22.04',
    'linux',
    'x64',
    'musl'
  ),
  platform('win32-arm64', 'aarch64-pc-windows-msvc', 'windows-11-arm', 'win32', 'arm64'),
  platform('win32-x64', 'x86_64-pc-windows-msvc', 'windows-2025', 'win32', 'x64'),
]

export function findSyncNativePlatform(
  os: NodeJS.Platform,
  cpu: NodeJS.Architecture,
  libc?: SyncNativeLibc
): SyncNativePlatform | undefined {
  return SYNC_NATIVE_PLATFORMS.find(
    (candidate) =>
      candidate.os === os &&
      candidate.cpu === cpu &&
      (candidate.os !== 'linux' || candidate.libc === libc)
  )
}

export function syncNativeMatrix(): string {
  return JSON.stringify({ include: SYNC_NATIVE_PLATFORMS })
}

export function renderSyncNativeShim(): string {
  const packages = SYNC_NATIVE_PLATFORMS.map(
    ({ os, cpu, libc, npmPackage, executable }) =>
      `  '${os}-${cpu}${libc ? `-${libc}` : ''}': {
    packageName: '${npmPackage}',
    binary: '${npmPackage}/bin/${executable}',
  },`
  ).join('\n')

  return `#!/usr/bin/env node
'use strict'

// generated by renderSyncNativeShim() in scripts/sync-native-platforms.ts.

const { createRequire } = require('node:module')
const { spawn } = require('node:child_process')
const { assertPortAvailable } = require('./port-check.cjs')

const PACKAGES = {
${packages}
}

const libc =
  process.platform === 'linux'
    ? process.report?.getReport().header.glibcVersionRuntime
      ? 'glibc'
      : 'musl'
    : undefined
const key = [process.platform, process.arch, libc].filter(Boolean).join('-')
const selected = PACKAGES[key]

if (!selected) {
  console.error(\`sync-native does not support \${key}\`)
  process.exit(1)
}

const load = createRequire(__filename)
let binary
try {
  const launcherVersion = load('../package.json').version
  const platformVersion = load(\`\${selected.packageName}/package.json\`).version
  if (platformVersion !== launcherVersion) {
    console.error(
      \`sync-native binary package for \${key} is \${platformVersion}, expected \${launcherVersion}. \` +
        'Reinstall orez-sync-native so its optional dependencies match.'
    )
    process.exit(1)
  }
  binary = load.resolve(selected.binary)
} catch (error) {
  console.error(
    \`sync-native binary package for \${key} is missing. \` +
      'Reinstall orez-sync-native without omitting optional dependencies.'
  )
  process.exit(1)
}

async function main() {
  const args = process.argv.slice(2)
  const parentPid = Number(process.env.OREZ_SYNC_NATIVE_PARENT_PID ?? process.ppid)
  const parentAlive = () => {
    if (process.ppid !== parentPid) return false
    try {
      process.kill(parentPid, 0)
      return true
    } catch (error) {
      if (error.code === 'ESRCH') return false
      if (error.code === 'EPERM') return true
      throw error
    }
  }
  let child
  let stopping = false
  let forceExit
  const stop = (signal = 'SIGTERM') => {
    if (stopping) return
    stopping = true
    if (!child) process.exit(1)
    child.kill(signal)
    forceExit = setTimeout(() => child.kill('SIGKILL'), 2000)
  }
  for (const signal of ['SIGINT', 'SIGTERM']) {
    process.on(signal, () => stop(signal))
  }
  // reparenting also catches SIGKILL, which cannot run the parent's cleanup.
  const parentWatch = setInterval(() => {
    if (!parentAlive()) stop()
  }, 100)
  try {
    if (args[0] === 'serve') {
      const portIndex = args.indexOf('--port')
      const hostIndex = args.indexOf('--host')
      if (portIndex >= 0) {
        await assertPortAvailable(
          Number(args[portIndex + 1]),
          hostIndex >= 0 ? args[hostIndex + 1] : undefined
        )
      }
    }
    if (!parentAlive()) return stop()
    child = spawn(binary, args, {
      // the pipe is owned only by this launcher. EOF kills the native host
      // even if the launcher itself is killed before it can forward a signal.
      stdio: ['pipe', 'inherit', 'inherit'],
      env: { ...process.env, OREZ_SYNC_NATIVE_PARENT_PIPE: '1' },
    })
    child.on('error', (error) => {
      console.error(\`sync-native could not start: \${error.message}\`)
      clearInterval(parentWatch)
      clearTimeout(forceExit)
      process.exitCode = 1
    })
    child.on('exit', (code, signal) => {
      clearInterval(parentWatch)
      clearTimeout(forceExit)
      if (!signal) {
        process.exitCode = code ?? 1
        return
      }
      process.removeAllListeners(signal)
      process.kill(process.pid, signal)
    })
  } catch (error) {
    clearInterval(parentWatch)
    console.error(\`sync-native: \${error.message}\`)
    process.exitCode = 1
  }
}

void main()
`
}
