#!/usr/bin/env bun
/**
 * run ~/chat e2e tests against local orez build.
 *
 * copies ~/chat to a temp dir (isolated from live edits), installs local
 * orez + bedrock-sqlite dist, then runs chat's playwright integration
 * tests in lite mode.
 *
 * usage:
 *   bun scripts/test-chat-e2e.ts                     # full build + test
 *   RETRY=1 bun scripts/test-chat-e2e.ts             # skip orez build + web rebuild
 *   bun scripts/test-chat-e2e.ts --filter=messaging   # filter tests
 *
 * env:
 *   RETRY=1        skip orez build + web rebuild (iterative mode)
 *   FILTER=pattern filter playwright tests
 *   PORT_OFFSET=N  override port offset (default: 400)
 */

import { execSync } from 'node:child_process'
import {
  existsSync,
  cpSync,
  rmSync,
  mkdirSync,
  writeFileSync,
  readFileSync,
  readdirSync,
  symlinkSync,
} from 'node:fs'
import { resolve } from 'node:path'

const OREZ_ROOT = resolve(import.meta.dirname, '..')
const CHAT_SOURCE = resolve(process.env.HOME!, 'chat')
const SQLITE_WASM_DIR = resolve(OREZ_ROOT, 'sqlite-wasm')
const TEST_DIR = resolve(OREZ_ROOT, 'test-chat')

const retry = process.env.RETRY === '1'
const filterArg = process.argv.find((a) => a.startsWith('--filter='))
const filter = filterArg?.split('=')[1] || process.env.FILTER || ''
// use 400 to avoid colliding with chat dev (0) or chat's own test offset (300)
const portOffset = process.env.PORT_OFFSET || '400'

function log(msg: string) {
  console.log(`\n\x1b[1m\x1b[36m[chat-e2e]\x1b[0m ${msg}`)
}

function main() {
  // step 0: validate ~/chat exists
  if (!existsSync(CHAT_SOURCE)) {
    console.error('~/chat does not exist, skipping')
    process.exit(0)
  }

  if (!existsSync(resolve(CHAT_SOURCE, 'package.json'))) {
    console.error('~/chat/package.json not found')
    process.exit(1)
  }

  // step 1: build orez (unless retry)
  if (!retry) {
    log('building orez...')
    execSync('bun run build', { cwd: OREZ_ROOT, stdio: 'inherit' })
  } else {
    log('RETRY mode: skipping orez build')
    if (!existsSync(resolve(OREZ_ROOT, 'dist'))) {
      console.error('dist/ not found - run without RETRY first')
      process.exit(1)
    }
  }

  // step 2: clone/sync ~/chat into test-chat/ (isolated from live edits)
  if (!retry || !existsSync(TEST_DIR)) {
    const chatRef = process.env.CHAT_REF || ''
    log(`cloning ~/chat → test-chat/${chatRef ? ` (ref: ${chatRef})` : ''}`)
    if (existsSync(TEST_DIR)) {
      rmSync(TEST_DIR, { recursive: true, force: true })
    }
    if (chatRef) {
      // full clone to allow checking out a specific commit
      execSync(`git clone "${CHAT_SOURCE}" "${TEST_DIR}"`, {
        stdio: 'inherit',
      })
      execSync(`git checkout ${chatRef}`, {
        cwd: TEST_DIR,
        stdio: 'inherit',
      })
    } else {
      execSync(`git clone --depth 1 "${CHAT_SOURCE}" "${TEST_DIR}"`, {
        stdio: 'inherit',
      })
    }

    // copy .env (secrets only - .env.development is auto-generated by env.ts)
    const envSrc = resolve(CHAT_SOURCE, '.env')
    if (existsSync(envSrc)) {
      cpSync(envSrc, resolve(TEST_DIR, '.env'))
    }

    // install deps
    log('installing dependencies...')
    execSync('bun install --ignore-scripts', {
      cwd: TEST_DIR,
      stdio: 'inherit',
      timeout: 300_000,
    })
    // run essential postinstall
    try {
      execSync('bun one patch', { cwd: TEST_DIR, stdio: 'inherit', timeout: 30_000 })
    } catch {}
    // build native @rocicorp/zero-sqlite3 (prebuild-install downloads prebuilt binary)
    log('building native @rocicorp/zero-sqlite3...')
    execSync('npm run install', {
      cwd: resolve(TEST_DIR, 'node_modules', '@rocicorp', 'zero-sqlite3'),
      stdio: 'inherit',
      timeout: 120_000,
    })
  } else {
    log('RETRY mode: reusing test-chat/')
    // sync critical source dirs so schema changes are picked up
    log('syncing src/ from ~/chat')
    for (const dir of [
      'src/database',
      'src/data',
      'src/server',
      'src/apps',
      'src/constants',
    ]) {
      const src = resolve(CHAT_SOURCE, dir)
      const dst = resolve(TEST_DIR, dir)
      if (existsSync(src)) {
        execSync(`rsync -a --delete "${src}/" "${dst}/"`, { stdio: 'inherit' })
      }
    }
    // sync e2e tests
    const e2eSrc = resolve(CHAT_SOURCE, 'src/integration/e2e')
    const e2eDst = resolve(TEST_DIR, 'src/integration/e2e')
    if (existsSync(e2eSrc)) {
      execSync(`rsync -a --delete "${e2eSrc}/" "${e2eDst}/"`, { stdio: 'inherit' })
    }
  }

  // write .env.development with offset ports
  // vite needs these to override production hostnames in .env
  const offset = Number(portOffset)
  const webPort = 8081 + offset
  const zeroPort = 5048 + offset
  const pgPort = 5632 + offset
  const minioPort = 9290 + offset
  const bunnyPort = 3533 + offset
  const envDev = [
    `# generated by test-chat-e2e.ts (PORT_OFFSET=${offset})`,
    `VITE_PROTOCOL="http"`,
    `VITE_PORT_WEB="${webPort}"`,
    `VITE_PORT_ZERO="${zeroPort}"`,
    `VITE_PORT_POSTGRES="${pgPort}"`,
    `VITE_PORT_MINIO="${minioPort}"`,
    `VITE_PORT_BUNNY="${bunnyPort}"`,
    `VITE_WEB_HOSTNAME="localhost:${webPort}"`,
    `VITE_ZERO_HOSTNAME="localhost:${zeroPort}"`,
    `BETTER_AUTH_SECRET="asjdbafbiasdjsadjasahjYVGHSVHFB"`,
    `BETTER_AUTH_URL="http://localhost:${webPort}"`,
    `ONE_SERVER_URL="http://localhost:${webPort}"`,
    `ZERO_UPSTREAM_DB="postgresql://user:password@127.0.0.1:${pgPort}/postgres"`,
    `ZERO_CVR_DB="postgresql://user:password@127.0.0.1:${pgPort}/zero_cvr"`,
    `ZERO_CHANGE_DB="postgresql://user:password@127.0.0.1:${pgPort}/zero_cdb"`,
    `ZERO_MUTATE_URL="http://localhost:${webPort}/api/zero/push"`,
    `ZERO_QUERY_URL="http://localhost:${webPort}/api/zero/pull"`,
    `CLOUDFLARE_R2_ACCESS_KEY="minio"`,
    `CLOUDFLARE_R2_ENDPOINT="http://localhost:${minioPort}/chat"`,
    `CLOUDFLARE_R2_PUBLIC_URL="http://localhost:${minioPort}/chat"`,
    `CLOUDFLARE_R2_SECRET_KEY="minio_password"`,
    `ALLOW_MISSING_ENV="1"`,
    `DO_NOT_TRACK="1"`,
  ].join('\n')
  log(`writing .env.development (PORT_OFFSET=${offset})`)
  writeFileSync(resolve(TEST_DIR, '.env.development'), envDev + '\n')

  // step 3: copy orez dist into test-chat/node_modules/orez
  log('installing local orez build')
  const orezDst = resolve(TEST_DIR, 'node_modules', 'orez')
  if (existsSync(orezDst)) {
    const orezDistDst = resolve(orezDst, 'dist')
    const orezSrcDst = resolve(orezDst, 'src')
    if (existsSync(orezDistDst)) rmSync(orezDistDst, { recursive: true, force: true })
    if (existsSync(orezSrcDst)) rmSync(orezSrcDst, { recursive: true, force: true })
  } else {
    mkdirSync(orezDst, { recursive: true })
  }
  cpSync(resolve(OREZ_ROOT, 'dist'), resolve(orezDst, 'dist'), { recursive: true })
  cpSync(resolve(OREZ_ROOT, 'package.json'), resolve(orezDst, 'package.json'))
  if (existsSync(resolve(OREZ_ROOT, 'src'))) {
    cpSync(resolve(OREZ_ROOT, 'src'), resolve(orezDst, 'src'), { recursive: true })
  }

  // step 4: copy bedrock-sqlite dist
  log('installing local bedrock-sqlite build')
  const sqliteDst = resolve(TEST_DIR, 'node_modules', 'bedrock-sqlite')
  if (existsSync(sqliteDst)) {
    const sqliteDistDst = resolve(sqliteDst, 'dist')
    if (existsSync(sqliteDistDst)) rmSync(sqliteDistDst, { recursive: true, force: true })
  } else {
    mkdirSync(sqliteDst, { recursive: true })
  }
  cpSync(resolve(SQLITE_WASM_DIR, 'dist'), resolve(sqliteDst, 'dist'), {
    recursive: true,
  })
  cpSync(resolve(SQLITE_WASM_DIR, 'package.json'), resolve(sqliteDst, 'package.json'))
  if (existsSync(resolve(SQLITE_WASM_DIR, 'bedrock-sqlite.d.ts'))) {
    cpSync(
      resolve(SQLITE_WASM_DIR, 'bedrock-sqlite.d.ts'),
      resolve(sqliteDst, 'bedrock-sqlite.d.ts')
    )
  }

  // ensure orez bin link is correct
  const binDir = resolve(TEST_DIR, 'node_modules', '.bin')
  const orezBinLink = resolve(binDir, 'orez')
  if (existsSync(orezBinLink)) rmSync(orezBinLink)
  symlinkSync(resolve(orezDst, 'dist', 'cli-entry.js'), orezBinLink)

  // patch lite:backend to use local orez binary (bun run orez resolves to global)
  // always start from source scripts to avoid double-patching
  const testPkgPath = resolve(TEST_DIR, 'package.json')
  const sourcePkg = JSON.parse(
    readFileSync(resolve(CHAT_SOURCE, 'package.json'), 'utf-8')
  )
  const testPkg = JSON.parse(readFileSync(testPkgPath, 'utf-8'))
  testPkg.scripts = { ...sourcePkg.scripts }
  const localOrezBin = resolve(orezDst, 'dist', 'cli-entry.js')
  if (testPkg.scripts['lite:backend']) {
    // replace bare `orez` command with absolute path to local cli-entry.js
    // `bun run:dev ./path/to/cli-entry.js` works because bun treats absolute/relative
    // paths as scripts to execute directly (unlike bare names which get resolved)
    testPkg.scripts['lite:backend'] = testPkg.scripts['lite:backend'].replace(
      /\borez\b/,
      `${localOrezBin} --disable-wasm-sqlite`
    )
    log(`patched lite:backend → ${localOrezBin} --disable-wasm-sqlite`)
  }
  writeFileSync(testPkgPath, JSON.stringify(testPkg, null, 2) + '\n')

  // step 5: skip wasm shim - use native @rocicorp/zero-sqlite3
  // (wasm shim had SQLITE_IOERR issues; native works reliably)
  log('using native @rocicorp/zero-sqlite3 (wasm disabled)')

  // step 6: build database migrations
  log('building database migrations')
  execSync('bun migrate build', {
    cwd: TEST_DIR,
    stdio: 'inherit',
    timeout: 120_000,
  })

  // step 7: clean .orez data dir (fresh state each run)
  // with PORT_OFFSET, env.ts sets OREZ_DATA_DIR=/tmp/orez-{offset}
  for (const dir of [resolve(TEST_DIR, '.orez'), `/tmp/orez-${portOffset}`]) {
    if (existsSync(dir)) {
      log(`cleaning ${dir}`)
      rmSync(dir, { recursive: true, force: true })
    }
  }

  // scale up assertion/wait timeouts across e2e tests and helpers for PGlite latency
  // PGlite is slower than postgres, so double timeouts as a buffer
  const e2eDir = resolve(TEST_DIR, 'src/integration/e2e')
  const scaleTimeout = (content: string): string => {
    // scale test.setTimeout() calls — floor at 180s (PGlite login + sync takes 60-90s)
    content = content.replace(
      /test\.setTimeout\(\s*(\d+)_?(\d*)\s*\)/g,
      (_match, major, minor) => {
        const ms = Number(major + (minor || ''))
        return `test.setTimeout(${Math.max(ms * 2, 180_000)})`
      }
    )
    // scale { timeout: N } assertion/wait timeouts 3x (but not 60_000+ timeouts)
    content = content.replace(/timeout:\s*(\d+)_?(\d*)\b/g, (_match, major, minor) => {
      const ms = Number(major + (minor || ''))
      if (ms >= 60_000) return _match // leave large timeouts alone
      return `timeout: ${ms * 3}`
    })
    // scale function default params: timeout = N, timeoutMs = N
    content = content.replace(
      /(timeout(?:Ms)?)\s*=\s*(\d+)_?(\d*)/g,
      (_match, name, major, minor) => {
        const ms = Number(major + (minor || ''))
        if (ms >= 60_000) return _match
        return `${name} = ${ms * 3}`
      }
    )
    return content
  }

  // bump loginAsAdmin timeouts in helpers.ts so the fast path has enough time
  // under PGlite and doesn't fall into the fallback path (which breaks when
  // the auth cookie is already set from the ?admin shortcut)
  const helpersPath = resolve(e2eDir, 'helpers.ts')
  if (existsSync(helpersPath)) {
    let helpers = readFileSync(helpersPath, 'utf-8')
    helpers = helpers.replace(
      `await page.locator('[data-username="admin"]').waitFor({\n      state: 'visible',\n      timeout: 15_000,\n    })`,
      `await page.locator('[data-username="admin"]').waitFor({\n      state: 'visible',\n      timeout: 60_000,\n    })`
    )
    // after loginAsAdmin confirms, wait for sidebar channels to sync from Zero
    // PGlite syncs user data (data-username) before channel data
    helpers = helpers.replace(
      `await dismissOnboarding(page)\n  await dismissViteOverlay(page)\n  console.info(\`✅ Logged in as admin\`)`,
      `await dismissOnboarding(page)\n  await dismissViteOverlay(page)\n  // wait for channel data to sync from zero (PGlite latency)\n  await page.locator('[data-testid^=\"channel-\"]').first().waitFor({ state: 'visible', timeout: 30_000 }).catch(() => {})\n  console.info(\`✅ Logged in as admin\`)`
    )
    // wait for pointer-events before clicking textbox in sendMessageIn
    // PGlite is slower to sync channel permissions, which gate pointer-events
    helpers = helpers.replace(
      `await channelInput.click()\n  await page.waitForTimeout(200)`,
      `await page.waitForFunction(\n    (testId) => {\n      const el = document.querySelector(\`[data-testid=\"\${testId}\"] [role=\"textbox\"]\`)\n      return el ? getComputedStyle(el).pointerEvents !== 'none' : false\n    },\n    \`\${inputName}-input\`,\n    { timeout: 30000 }\n  ).catch(() => {})\n  await channelInput.click()\n  await page.waitForTimeout(200)`
    )
    // stabilize hoverMessage: wait for message element to be attached before scrolling
    // under PGlite, Zero resync can re-render the message list, detaching DOM elements
    helpers = helpers.replace(
      `await directEl.scrollIntoViewIfNeeded()`,
      `await directEl.waitFor({ state: 'attached', timeout: 10_000 })\n    await directEl.scrollIntoViewIfNeeded()`
    )
    // after loginAsUser, wait for sidebar channels to sync from Zero
    helpers = helpers.replace(
      `await dismissOnboarding(page)\n  await dismissViteOverlay(page)\n  await dismissHud(page)\n  console.info(\`Logged in as \${email}\`)`,
      `await dismissOnboarding(page)\n  await dismissViteOverlay(page)\n  await dismissHud(page)\n  // wait for channel data to sync from zero (PGlite latency)\n  await page.locator('[data-testid^=\"channel-\"]').first().waitFor({ state: 'visible', timeout: 30_000 }).catch(() => {})\n  console.info(\`Logged in as \${email}\`)`
    )
    writeFileSync(helpersPath, helpers)
  }

  // patch all .ts files in e2e dir
  log('scaling e2e assertion timeouts 3x for PGlite latency')
  for (const entry of readdirSync(e2eDir)) {
    if (!entry.endsWith('.ts')) continue
    // global.setup.ts gets scaled too (e.g. waitForURL 45s → 90s)
    const filePath = resolve(e2eDir, entry)
    const content = readFileSync(filePath, 'utf-8')
    const patched = scaleTimeout(content)
    if (patched !== content) {
      writeFileSync(filePath, patched)
    }
  }

  // permissions-messages readonly test: channel permissions sync is slow under PGlite
  // the 3x scaled timeout (30s) isn't enough — bump to 60s
  const permMsgsPath = resolve(e2eDir, 'permissions-messages.test.ts')
  if (existsSync(permMsgsPath)) {
    let permMsgs = readFileSync(permMsgsPath, 'utf-8')
    // bump the "Unable to post" assertion timeout (already 30000 from 3x scaling)
    permMsgs = permMsgs.replace(
      /Unable to post in this channel.*?timeout:\s*(\d+)/s,
      (match, timeout) => match.replace(`timeout: ${timeout}`, 'timeout: 60000')
    )
    writeFileSync(permMsgsPath, permMsgs)
  }

  // adjust playwright config for PGlite: bump default timeout, disable maxFailures
  for (const cfgPath of [
    resolve(TEST_DIR, 'playwright.config.ts'),
    resolve(TEST_DIR, 'src/integration/playwright.config.ts'),
  ]) {
    if (existsSync(cfgPath)) {
      let cfg = readFileSync(cfgPath, 'utf-8')
      cfg = cfg.replace(/timeout:\s*20\s*\*\s*1000,/, 'timeout: 60 * 1000,')
      // limit workers to reduce PGlite contention
      cfg = cfg.replace(/fullyParallel:\s*false,/, 'fullyParallel: false,\n  workers: 2,')
      // disable maxFailures so one slow test doesn't interrupt others
      cfg = cfg.replace(/maxFailures:\s*\d+/, 'maxFailures: 0')
      // ensure retries are disabled (tests must genuinely pass)
      cfg = cfg.replace(/retries:\s*\d+/, 'retries: 0')
      writeFileSync(cfgPath, cfg)
    }
  }

  // bump tko test runner timeout for playwright (default 10min is tight for PGlite)
  const tkoE2ePath = resolve(TEST_DIR, 'scripts/test/e2e.ts')
  if (existsSync(tkoE2ePath)) {
    let e2e = readFileSync(tkoE2ePath, 'utf-8')
    e2e = e2e.replace(
      /timeout:\s*time\.ms\.minutes\(\d+\)/g,
      'timeout: time.ms.minutes(15)'
    )
    writeFileSync(tkoE2ePath, e2e)
  }

  log('local packages installed')

  // verify we're using local orez, not global
  const localOrezVersion = JSON.parse(
    readFileSync(resolve(orezDst, 'package.json'), 'utf-8')
  ).version
  log(`orez version: ${localOrezVersion} (local build)`)

  // kill any stale processes on our offset ports from previous runs
  const testPorts = [
    8081 + offset,
    5048 + offset,
    5632 + offset,
    9290 + offset,
    3533 + offset,
  ]
  for (const p of testPorts) {
    try {
      execSync(`lsof -ti:${p} | xargs kill -9 2>/dev/null`, { stdio: 'ignore' })
    } catch {}
  }

  // step 8: run chat e2e tests in lite mode
  const testCmd = ['bun', 'run', 'test', 'e2e', '--integration', '--lite']
  if (retry) testCmd.push('--retry')
  if (filter) testCmd.push('--filter', filter)

  log(`running: ${testCmd.join(' ')}`)
  log(`PORT_OFFSET=${portOffset}`)

  // prepend node_modules/.bin to PATH so local orez is used instead of global
  const localPath = `${binDir}:${process.env.PATH}`

  try {
    execSync(testCmd.join(' '), {
      cwd: TEST_DIR,
      stdio: 'inherit',
      timeout: 1_200_000,
      env: {
        ...process.env,
        PATH: localPath,
        PORT_OFFSET: portOffset,
        NODE_ENV: 'development',
        ALLOW_MISSING_ENV: '1',
      },
    })
    log('TESTS PASSED')
  } catch (err: any) {
    log('TESTS FAILED')
    process.exit(err.status || 1)
  }
}

main()
